import {MD3DarkTheme, MD3LightTheme} from 'react-native-paper';

export const DarkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    PrimaryButton: '#4A90E2',
    SecondaryButton: '##FFFFFF',
    Primary: '#1A1A1A',
    PrimaryText: '#1A1A1A',
    SecondaryText: '#4A4A4A',
    MutedText: '#9E9E9E',
    InvertedText: '#FFFFFF',
    PrimaryRounded: 8,
    SecondaryRounded: 80,
    BrightWhite: '#FFFFFF',
    LightGray: '#F9F9F9',
    SlateGray: '#4A4A4A',
    MutedGray: '#9E9E9E',
    PitchBlack: '#1A1A1A',
    DefaultIcons: '#9E9E9E',
    ActiveIcons: '#4A90E2',
    DarkModeColor: '#1A1A1A',
    PrimaryDarkBackground: '#121212',
    MelodicBlueTint: '#EAF4FC',
    HarmonyPurpleTint: '#EDE3F4',

    headerIconColor: '#1E232C',
    iconBorderColor: '#E8ECF4',
    buttonBlack: '#111111',
    black: '#111111',
    dividerTextLine: '#E8ECF4',
    grayShadeLight: '#6A707C',
    skyBlueShade: '#35C2C1',
    labelBlack: '#333333',
  },
};

export const LightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    PrimaryButton: '#4A90E2',
    SecondaryButton: '##FFFFFF',
    Primary: '#1A1A1A',
    PrimaryText: '#1A1A1A',
    SecondaryText: '#4A4A4A',
    MutedText: '#9E9E9E',
    InvertedText: '#FFFFFF',
    PrimaryRounded: 8,
    SecondaryRounded: 80,
    BrightWhite: '#FFFFFF',
    LightGray: '#F9F9F9',
    SlateGray: '#4A4A4A',
    MutedGray: '#9E9E9E',
    PitchBlack: '#1A1A1A',
    DefaultIcons: '#9E9E9E',
    ActiveIcons: '#4A90E2',
    LightModeColor: '#FFFFFF',
    PrimaryLightBackground: '#FFFFFF',
    MelodicBlueTint: '#EAF4FC',
    HarmonyPurpleTint: '#EDE3F4',

    headerIconColor: '#1E232C',
    iconBorderColor: '#E8ECF4',
    white: '#FFFFFF',
    buttonBlack: '#111111',
    black: '#111111',
    dividerTextLine: '#E8ECF4',
    grayShadeLight: '#6A707C',
    skyBlueShade: '#35C2C1',
    labelBlack: '#333333',
  },
};
